# Esercizio 1: QW sull'anello

Calcolare la distribuzione di probabilità di un QW continuo nel tempo su un grafo ad anello, in funzione del tempo.


In [3]:
#inizializzare i pacchetti
#...
import numpy as np
import matplotlib.pyplot as plt  #pacchetto per fare i grafici
import scipy.linalg as sla

In [9]:
#Inizializzare la funzione d'onda del walker localizzata su un singolo sito
#e definire i parametri
#...
Nsites=15 #scegliere il numero di nodi
gamma=1   #jumping rate
#...
psi0=np.zeros(Nsites,dtype=complex)
psi0[0]=1
print(psi0)
print("norma:",np.linalg.norm(psi0))

[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
norma: 1.0


In [11]:
#Scrivere l'Hamiltoniana (Laplaciano)
#...
ham=np.zeros((Nsites,Nsites))
#...
print(ham)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
#calcolare l'evoluzione temporale delle probabilità
#...


In [15]:
#Plottare la distribuzione di probabilità sui siti del grafo per diversi valori del tempo
#si veda il pacchetto matplotlib per fare plot con il plt.plot
#oppure
#si può fare un grafico a barre:

## make data:
#tempo=0.5
#x = np.arange(Nsites)#siti
#y = DISTRIBUZIONE_PROBABILITA'(tempo)

## plot
#fig, ax = plt.subplots()
#ax.bar(x, y, width=0.7)
#ax.set(xticks=np.arange(0, Nsites),xlim=(0, Nsites), yticks=np.arange(0, 1))

#ax.set_title('Probability ditribution at time t='+str(tt))
#plt.show()


### Richiesta:
Dimostrare che la distribuzione di probabilità non cambia se invece del Laplaciano di considera solamente la matrice di adiacenza come Hamiltoniana.